# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef0f5464ff5fd5a02e0c8daff3b860230769af33ce17dc157f0bc2eacff00f2a488bbaaefed62906956674da2b7da4a482cb2671d2a0a9d1981d35579698a83

test:
  secret_key_base: 93965f3fded685197b61900d0022bca73b9d51c43b35b97896418cbad0a908993d7116083742036217cfd93ca2cee407800ff5b70cee695add53088a85aa7c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
